logging:
  level:
    ROOT: WARN
    uni.app.dondeestaciono: WARN
spring:
  http:
    log-request-details: true
  data:
    mongodb:
      database: dondeestaciono
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  error:
    whitelabel:
      enabled: false
firebase:
  url: https://dondeestaciono-2350.firebaseio.com
  json-path: C:\\Users\\josue\\donde_estaciono-firebase.json
caba:
  urls:
    estacionamientos: /transito/v1/estacionamientos
    normalizador: /normalizar
twitter:
  debug: true
