logging:
  level:
    ROOT: INFO
    uni.app.dondeestaciono: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
spring:
  data:
    mongodb:
      database: dondeestaciono
server:
  error:
    whitelabel:
      enabled: true